import type { CommunityDrive, LeaderboardEntry, TreeType } from '../types';

export const MOCK_DRIVES: CommunityDrive[] = [
    {
        id: 'cd-001',
        title: 'Mega Tree Plantation Drive',
        description: 'Join us to plant 500 saplings across the Pusa Road corridor. Tools and saplings will be provided by the municipality.',
        type: 'plantation',
        date: 'This Sunday, 8:00 AM',
        location: 'Pusa Road, Central Zone',
        authorityName: 'NDMC Forestry Dept.',
        participantsCount: 142,
    },
    {
        id: 'cd-002',
        title: 'Ghaffar Market Cleanliness Drive',
        description: 'A community effort to clear plastic waste and promote proper waste segregation in major market areas.',
        type: 'cleanliness',
        date: 'Next Saturday, 7:00 AM',
        location: 'Ghaffar Market',
        authorityName: 'MCD Sanitation',
        participantsCount: 89,
    },
    {
        id: 'cd-003',
        title: 'Dengue Awareness Campaign',
        description: 'Door-to-door awareness campaign about preventing water stagnation to curb dengue outbreaks.',
        type: 'awareness',
        date: 'Tomorrow, 10:00 AM',
        location: 'Karol Bagh Residential Blocks',
        authorityName: 'Dept of Public Health',
        participantsCount: 34,
    },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
    {
        rank: 1,
        userId: 'u-1',
        userName: 'Aarav Sharma',
        civicScore: 450,
        treesAdopted: 12,
        drivesJoined: 8,
        issuesReported: 15,
    },
    {
        rank: 2,
        userId: 'u-2',
        userName: 'Priya Patel',
        civicScore: 425,
        treesAdopted: 15,
        drivesJoined: 5,
        issuesReported: 10,
    },
    {
        rank: 3,
        userId: 'u-3',
        userName: 'Rahul Verma',
        civicScore: 380,
        treesAdopted: 8,
        drivesJoined: 10,
        issuesReported: 11,
    },
    {
        rank: 4,
        userId: 'u-4',
        userName: 'Neha Gupta',
        civicScore: 310,
        treesAdopted: 5,
        drivesJoined: 6,
        issuesReported: 9,
    },
    {
        rank: 5,
        userId: 'u-5',
        userName: 'Karan Singh',
        civicScore: 295,
        treesAdopted: 7,
        drivesJoined: 4,
        issuesReported: 7,
    },
];

export const TREE_TYPES: { id: TreeType; name: string }[] = [
    { id: 'neem', name: 'Neem' },
    { id: 'peepal', name: 'Peepal' },
    { id: 'banyan', name: 'Banyan' },
    { id: 'mango', name: 'Mango' },
    { id: 'ashoka', name: 'Ashoka' },
    { id: 'gulmohar', name: 'Gulmohar' },
    { id: 'coconut', name: 'Coconut' },
    { id: 'other', name: 'Other' },
];

export const MOCK_CITIZEN_DRIVES: import('../types').CitizenDrive[] = [
    {
        id: 'cd-citizen-001',
        issueId: 'i-001',
        issueTitle: 'Pothole on Main Street causes accidents',
        title: 'Fix Potholes Together — Karol Bagh',
        description: 'Volunteers to fill temporary gravel patches on the pothole stretches until MCD takes formal action.',
        type: 'volunteering',
        date: 'Next Saturday, 8:00 AM',
        location: 'Karol Bagh, Central Delhi',
        locality: 'karol bagh',
        createdBy: 'Arjun Mehta',
        target: 30,
        participantsCount: 22,
        status: 'gathering',
    },
    {
        id: 'cd-citizen-002',
        issueId: 'i-002',
        issueTitle: 'Dead trees along the Ring Road corridor',
        title: 'Ring Road Saplings Plantation Drive',
        description: 'Citizens planting 100 native saplings along the dead tree zones, funded by local community collection.',
        type: 'plantation',
        date: 'This Sunday, 7:30 AM',
        location: 'Ring Road, South Delhi',
        locality: 'ring road',
        createdBy: 'Priya Nair',
        target: 50,
        participantsCount: 50,
        status: 'active',
    },
    {
        id: 'cd-citizen-003',
        issueId: 'i-003',
        issueTitle: 'Overflowing garbage near residential blocks',
        title: 'Community Cleanup — Lajpat Nagar',
        description: 'Proposed neighborhood clean-up drive targeting specific blocks with chronic garbage overflow.',
        type: 'cleanliness',
        location: 'Lajpat Nagar Block C',
        locality: 'lajpat nagar',
        createdBy: 'Rahul Sen',
        target: 40,
        participantsCount: 11,
        status: 'proposed',
    },
    {
        id: 'cd-citizen-004',
        issueId: 'i-004',
        issueTitle: 'Poor streetlight coverage in Rajinder Nagar',
        title: 'Street Safety Awareness Walk — Rajinder Nagar',
        description: 'Community walk to document faulty streetlights and submit a consolidated report to the municipality.',
        type: 'awareness',
        date: 'Last week',
        location: 'Rajinder Nagar, Block 4',
        locality: 'rajinder nagar',
        createdBy: 'Meena Saxena',
        target: 25,
        participantsCount: 31,
        status: 'completed',
    },
    {
        id: 'cd-citizen-005',
        issueId: 'i-005',
        issueTitle: 'Stray animal menace near school',
        title: 'Animal Safety Drive — Pusa Road',
        description: 'Awareness drive on co-existing safely with stray animals; includes sterilisation camp coordination.',
        type: 'health-safety',
        location: 'Pusa Road, Near Delhi University Gate',
        locality: 'pusa road',
        createdBy: 'Vikram Joshi',
        target: 60,
        participantsCount: 4,
        status: 'expired',
    },
    {
        id: 'cd-citizen-006',
        issueId: 'i-001',
        issueTitle: 'Pothole on Main Street causes accidents',
        title: 'Road Safety Volunteer Drive — Karol Bagh (Merged)',
        description: 'Merged from a duplicate request. Combined effort to fix potholes and install temporary signage.',
        type: 'volunteering',
        date: 'Next Saturday, 8:00 AM',
        location: 'Karol Bagh Sector 2',
        locality: 'karol bagh',
        createdBy: 'Sonia Rawat',
        target: 30,
        participantsCount: 22,  // merged into cd-citizen-001
        status: 'gathering',
    },
];

