import type { Issue } from '../types';

/** Helper – produces an ISO date string N days ago */
const daysAgo = (n: number): string => {
    const d = new Date();
    d.setDate(d.getDate() - n);
    return d.toISOString();
};

export const MOCK_ISSUES: Issue[] = [
    {
        id: 'i1',
        title: 'Garbage piling up near Ajmal Khan Park',
        description:
            'Large amounts of household and commercial waste have been accumulating for the past 4 days near the east gate of Ajmal Khan Park. The stench is unbearable and attracting stray animals.',
        category: 'sanitation-waste',
        severity: 'high',
        status: 'reported',
        location: { area: 'Ajmal Khan Road', ward: 'Ward 52', municipalZone: 'Karol Bagh Zone', constituency: 'Karol Bagh' },
        reportedBy: 'u1',
        isAnonymous: false,
        upvotes: 14,
        upvotedBy: ['u2', 'u3'],
        createdAt: daysAgo(2),
        updatedAt: daysAgo(2),
    },
    {
        id: 'i2',
        title: 'Pothole on Pusa Road causing accidents',
        description:
            'A deep pothole has formed on Pusa Road near the metro station exit. Two-wheelers are especially at risk. Multiple minor accidents reported.',
        category: 'roads-infrastructure',
        severity: 'critical',
        status: 'in-progress',
        location: { area: 'Pusa Road', ward: 'Ward 52', municipalZone: 'Karol Bagh Zone', constituency: 'Karol Bagh' },
        reportedBy: 'u2',
        isAnonymous: false,
        upvotes: 23,
        upvotedBy: ['u1', 'u3'],
        createdAt: daysAgo(5),
        updatedAt: daysAgo(1),
    },
    {
        id: 'i3',
        title: 'Streetlight not working on Arya Samaj Road',
        description:
            'The streetlight near House No. 34, Arya Samaj Road has been non-functional for over a week. The stretch becomes very dark and unsafe after 7 PM.',
        category: 'streetlights-electricity',
        severity: 'medium',
        status: 'assigned',
        location: { area: 'Arya Samaj Road', ward: 'Ward 53', municipalZone: 'Karol Bagh Zone', constituency: 'Karol Bagh' },
        reportedBy: 'u3',
        isAnonymous: false,
        upvotes: 7,
        upvotedBy: ['u1'],
        createdAt: daysAgo(8),
        updatedAt: daysAgo(3),
    },
    {
        id: 'i4',
        title: 'Sewage overflow in Shankar Road gali',
        description:
            'Open drain in the inner gali of Shankar Road has been overflowing since the last rain. Sewage water is entering homes on the ground floor.',
        category: 'water-drainage',
        severity: 'critical',
        status: 'under-review',
        location: { area: 'Shankar Road', ward: 'Ward 50', municipalZone: 'Rajinder Nagar Zone', constituency: 'Rajinder Nagar' },
        reportedBy: 'u2',
        isAnonymous: true,
        upvotes: 19,
        upvotedBy: ['u1', 'u3'],
        createdAt: daysAgo(3),
        updatedAt: daysAgo(2),
    },
    {
        id: 'i5',
        title: 'Stray dogs aggressive near Market No. 2',
        description:
            'A pack of stray dogs near Rajinder Nagar Market No. 2 has become increasingly aggressive towards morning walkers and children. Urgent action needed.',
        category: 'animal-human-conflict',
        severity: 'high',
        status: 'reported',
        location: { area: 'Market No. 2', ward: 'Ward 50', municipalZone: 'Rajinder Nagar Zone', constituency: 'Rajinder Nagar' },
        reportedBy: 'u1',
        isAnonymous: false,
        upvotes: 11,
        upvotedBy: ['u2'],
        createdAt: daysAgo(1),
        updatedAt: daysAgo(1),
    },
    {
        id: 'i6',
        title: 'Illegal dumping behind community center',
        description:
            'Construction debris and household waste is being illegally dumped behind the Karol Bagh Community Center. This is damaging the park area adjacent to it.',
        category: 'environment-damage',
        severity: 'medium',
        status: 'reported',
        location: { area: 'Community Center', ward: 'Ward 52', municipalZone: 'Karol Bagh Zone', constituency: 'Karol Bagh' },
        reportedBy: 'u3',
        isAnonymous: true,
        upvotes: 5,
        upvotedBy: [],
        createdAt: daysAgo(4),
        updatedAt: daysAgo(4),
    },
    {
        id: 'i7',
        title: 'Mosquito breeding in stagnant water near park',
        description:
            'Stagnant water has collected in an abandoned plot next to the children\'s park in Ward 53. Mosquito infestation is increasing, raising dengue concerns.',
        category: 'public-health',
        severity: 'high',
        status: 'assigned',
        location: { area: 'Children\'s Park', ward: 'Ward 53', municipalZone: 'Karol Bagh Zone', constituency: 'Karol Bagh' },
        reportedBy: 'u1',
        isAnonymous: false,
        upvotes: 16,
        upvotedBy: ['u2', 'u3'],
        createdAt: daysAgo(6),
        updatedAt: daysAgo(2),
    },
    {
        id: 'i8',
        title: 'Road blocked by encroachment on DB Gupta Road',
        description:
            'Vendors have encroached significantly onto DB Gupta Road footpath, forcing pedestrians to walk on the main road. This is especially dangerous during rush hours.',
        category: 'illegal-encroachment',
        severity: 'medium',
        status: 'resolved',
        location: { area: 'DB Gupta Road', ward: 'Ward 52', municipalZone: 'Karol Bagh Zone', constituency: 'Karol Bagh' },
        reportedBy: 'u2',
        isAnonymous: false,
        upvotes: 9,
        upvotedBy: ['u1'],
        createdAt: daysAgo(12),
        updatedAt: daysAgo(1),
    },
    {
        id: 'i9',
        title: 'Broken bench and damaged railing in Nai Sarak park',
        description:
            'The main bench and side railing at Nai Sarak pocket park are damaged. The broken railing has sharp edges and is hazardous for children.',
        category: 'public-property-damage',
        severity: 'low',
        status: 'closed',
        location: { area: 'Nai Sarak', ward: 'Ward 53', municipalZone: 'Karol Bagh Zone', constituency: 'Karol Bagh' },
        reportedBy: 'u3',
        isAnonymous: false,
        upvotes: 3,
        upvotedBy: [],
        createdAt: daysAgo(20),
        updatedAt: daysAgo(5),
    },
    {
        id: 'i10',
        title: 'Excessive loudspeaker noise from marriage hall',
        description:
            'The marriage hall near Ghaffar Market has been using loudspeakers well past 10 PM for the last 3 nights. Residents are unable to sleep.',
        category: 'noise-nuisance',
        severity: 'medium',
        status: 'reported',
        location: { area: 'Ghaffar Market', ward: 'Ward 52', municipalZone: 'Karol Bagh Zone', constituency: 'Karol Bagh' },
        reportedBy: 'u1',
        isAnonymous: true,
        upvotes: 8,
        upvotedBy: ['u2'],
        createdAt: daysAgo(1),
        updatedAt: daysAgo(1),
    },
    {
        id: 'i11',
        title: 'Exposed electric wires near bus stop',
        description:
            'Dangling electric wires near the Karol Bagh Metro bus stop are a serious electrocution hazard, especially during rain.',
        category: 'citizen-safety',
        severity: 'critical',
        status: 'in-progress',
        location: { area: 'Karol Bagh Metro', ward: 'Ward 52', municipalZone: 'Karol Bagh Zone', constituency: 'Karol Bagh' },
        reportedBy: 'u2',
        isAnonymous: false,
        upvotes: 27,
        upvotedBy: ['u1', 'u3'],
        createdAt: daysAgo(7),
        updatedAt: daysAgo(1),
    },
    {
        id: 'i12',
        title: 'Water leakage from main pipeline on Rohtak Road',
        description:
            'A major water pipeline leak on Rohtak Road is wasting thousands of litres daily. The road surface is also degrading due to constant water flow.',
        category: 'water-drainage',
        severity: 'high',
        status: 'under-review',
        location: { area: 'Rohtak Road', ward: 'Ward 50', municipalZone: 'Rajinder Nagar Zone', constituency: 'Rajinder Nagar' },
        reportedBy: 'u3',
        isAnonymous: false,
        upvotes: 15,
        upvotedBy: ['u1', 'u2'],
        createdAt: daysAgo(4),
        updatedAt: daysAgo(3),
    },
];
